libaries:
- name: dbooks
  version: 1
- name: numpy
  version: "1.6.1"


 handlers:
- url: /robots.txt
  static_path: robots.txt
- url: /favicon.ico
  static_path: favicon.ico
- url: /static/
  static_path: app_package/static